// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using status_formaner_API.Data;

#nullable disable

namespace status_formaner_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326232718_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("status_formaner_API.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminComment")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusOBJ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCommemt")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("status_formaner_API.Models.ServiceStatus", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServicID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID", "ServicID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("ServiceStatus", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
