// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapportAPI.Data;

#nullable disable

namespace RapportAPI.Migrations
{
    [DbContext(typeof(DatabasContext))]
    [Migration("20260328110713_AddRapportPost")]
    partial class AddRapportPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("RapportAPI.Models.Ansokan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Beviljad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedarbetarNamn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormanId");

                    b.ToTable("Ansokningar");
                });

            modelBuilder.Entity("RapportAPI.Models.Forman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kostnad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Formaner");
                });

            modelBuilder.Entity("RapportAPI.Models.RapportPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntalAktivaFormaner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avdelning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SkapadDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalKostnad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RapportPoster");
                });

            modelBuilder.Entity("RapportAPI.Models.Ansokan", b =>
                {
                    b.HasOne("RapportAPI.Models.Forman", "Forman")
                        .WithMany("Ansokningar")
                        .HasForeignKey("FormanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forman");
                });

            modelBuilder.Entity("RapportAPI.Models.Forman", b =>
                {
                    b.Navigation("Ansokningar");
                });
#pragma warning restore 612, 618
        }
    }
}
